#!/usr/bin/with-contenv bash

# make our folders and links
mkdir -p \
	/config/{log/fail2ban,fail2ban,crontabs,geoip2db} \
	/var/run/fail2ban

# copy/update the fail2ban config defaults to/in /config
cp -R /defaults/fail2ban/filter.d /config/fail2ban/
cp -R /defaults/fail2ban/action.d /config/fail2ban/
# if jail.local is missing in /config, copy default
[[ ! -f /config/fail2ban/jail.local ]] && \
    cp /defaults/jail.local /config/fail2ban/jail.local
# Replace fail2ban config with user config
[[ -d /etc/fail2ban/filter.d ]] && \
    rm -rf /etc/fail2ban/filter.d
[[ -d /etc/fail2ban/action.d ]] && \
    rm -rf /etc/fail2ban/action.d
cp -R /config/fail2ban/filter.d /etc/fail2ban/
cp -R /config/fail2ban/action.d /etc/fail2ban/
cp /defaults/fail2ban/fail2ban.local /etc/fail2ban/
cp /config/fail2ban/jail.local /etc/fail2ban/jail.local

# always copy a new logrotate crontab file to prevent problems
cp /etc/crontabs/logrotate /config/crontabs/

# remove lua bits from nginx.conf if not done before
if ! grep -q '#Removed lua' /config/nginx/nginx.conf; then
  echo "Removing lua specific info from nginx.conf"
  sed -i 's|\tlua_load_resty_core off;|\t#Removed lua. Do not remove this comment|g' /config/nginx/nginx.conf
fi

# import user crontabs
rm /etc/crontabs/*
cp /config/crontabs/* /etc/crontabs/

# create GeoIP2 folder symlink
[[ -d /var/lib/libmaxminddb ]] && [[ ! -L /var/lib/libmaxminddb ]] && \
  rm -rf /var/lib/libmaxminddb
[[ ! -d /var/lib/libmaxminddb ]] && \
  ln -s /config/geoip2db /var/lib/libmaxminddb
# check GeoIP2 database
if [ -f /var/lib/libmaxminddb/GeoLite2-City.mmdb ]; then
  echo "GeoIP2 database found"
else
  echo "Starting 2019/12/30, GeoIP2 databases require personal license key to download. Please manually download/update the GeoIP2 db and save as /config/geoip2db/GeoLite2-City.mmdb"
fi

# logfiles needed by fail2ban
[[ ! -f /config/log/nginx/error.log ]] && \
    touch /config/log/nginx/error.log
[[ ! -f /config/log/nginx/access.log ]] && \
    touch /config/log/nginx/access.log

# permissions
chmod -R 0644 /etc/logrotate.d
chmod -R +r /config/log
