#!/usr/bin/with-contenv bash

# determine if setup is needed for ubuntu
if [ ! -f /usr/sbin/cron ] && \
[ -f /usr/bin/apt ]; then
    # install cron
    apt-get update
    apt-get install --no-install-recommends -y \
        cron
fi

# make folders if not exist
[[ ! -d /config/crontabs ]] && \
 mkdir -p /config/crontabs



# if root crontabs do not exist in config
# copy root crontab from system
if [[ ! -f /config/crontabs/root ]] && \
crontab -l -u root; then
	crontab -l -u root > /config/crontabs/root
fi

# if root crontabs still do not exist in config (were not copied from system)
# copy root crontab from included defaults
[[ ! -f /config/crontabs/root ]] && \
	cp /etc/crontabs/root /config/crontabs/

# if user crontabs do not exist in config
# copy user crontab from system
if [[ ! -f /config/crontabs/user ]] && \
crontab -l -u abc; then
	crontab -l -u abc > /config/crontabs/user
fi

# if user crontabs still do not exist in config (were not copied from system)
# copy user crontab from included defaults
[[ ! -f /config/crontabs/user ]] && \
	cp /etc/crontabs/user /config/crontabs/


# import user crontabs
crontab -u root /config/crontabs/root
crontab -u abc /config/crontabs/user
